# Q-Table Learning

In [3]:
import gym
import numpy as np

### Load the environment

In [4]:
env = gym.make('FrozenLake-v0')

[2017-09-19 00:14:00,378] Making new env: FrozenLake-v0


### Implement Q-Table learning algorithm

In [5]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [6]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.3415


In [7]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  0.00000000e+00   3.21659325e-03   7.11258741e-02   3.77275278e-03]
 [  1.40142926e-04   6.28663593e-04   3.82537963e-04   5.70357100e-02]
 [  1.11334221e-03   1.71547211e-03   5.03560745e-03   2.70581149e-02]
 [  1.21489905e-04   1.26054020e-06   1.51142168e-04   1.15547388e-02]
 [  1.21808902e-01   3.85409984e-04   2.56107337e-03   4.44290995e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.33587701e-04   4.78696801e-06   9.09548187e-03   3.22661233e-07]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.03374296e-04   4.37830905e-04   0.00000000e+00   1.10981873e-01]
 [  1.21048450e-03   3.15300523e-01   7.05293251e-04   2.38701727e-03]
 [  7.06823321e-01   1.85555185e-04   4.56897106e-04   5.51566668e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.31919608e-03   4.88860484e-01   1